services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - BiLabNetwork
    ports:
      - "3306:3306"
    #command: [ "--default-authentication-plugin=mysql_native_password" ]
  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./metabase-data:/metabase-data
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - BiLabNetwork
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  BiLabNetwork:
    driver: bridge