executor: parallel
tasks:
  - source: ./etl/extract/extract.py
    name: extract
    product:
      nb: ./etl/extract/output/extract.ipynb
    params:
      extract_path: '{{extract_path}}'
  - source: ./etl/transform/clean/clean_weather.py
    name: clean_weather
    product:
      data: '{{transform_path}}/clean/clean_weather.csv'
      nb: ./etl/transform/clean/output/clean_weather.ipynb
    params:
      extract_path: '{{extract_path}}'
      transform_path: '{{transform_path}}'
  - source: ./etl/transform/migrations/temperature_categories.py
    name: create_temperature_categories
    product:
      data: '{{transform_path}}/migrations/temperature_categories.csv'
      nb: ./etl/transform/migrations/output/temperature_categories.ipynb
    params:
      transform_path: '{{transform_path}}'
  - source: ./etl/transform/migrations/wind_levels.py
    name: create_wind_levels
    product:
      data: '{{transform_path}}/migrations/wind_levels.csv'
      nb: ./etl/transform/migrations/output/wind_levels.ipynb
    params:
      transform_path: '{{transform_path}}'
  - source: ./etl/transform/migrations/age_groups.py
    name: create_age_groups
    product:
      data: '{{transform_path}}/migrations/age_groups.csv'
      nb: ./etl/transform/migrations/output/age_groups.ipynb
    params:
      extract_path: '{{extract_path}}'
      transform_path: '{{transform_path}}'
  - source: ./etl/transform/migrations/countries.py
    name: create_countries
    product:
      data: '{{transform_path}}/migrations/countries.csv'
      nb: ./etl/transform/migrations/output/countries.ipynb
    params:
      extract_path: '{{extract_path}}'
      transform_path: '{{transform_path}}'
  - source: ./etl/transform/migrations/country_populations.py
    name: create_country_populations
    product:
      data: '{{transform_path}}/migrations/country_populations.csv'
      nb: ./etl/transform/migrations/output/country_populations.ipynb
    params:
      extract_path: '{{extract_path}}'
      transform_path: '{{transform_path}}'
  - source: ./etl/transform/migrations/prognosis.py
    name: create_prognosis
    product:
      data: '{{transform_path}}/migrations/prognosis.csv'
      nb: ./etl/transform/migrations/output/prognosis.ipynb
    params:
      extract_path: '{{extract_path}}'
      transform_path: '{{transform_path}}'
  - source: ./etl/transform/migrations/timezones.py
    name: create_timezones
    product:
      data: '{{transform_path}}/migrations/timezones.csv'
      nb: ./etl/transform/migrations/output/timezones.ipynb
    params:
      extract_path: '{{extract_path}}'
      transform_path: '{{transform_path}}'
  - source: ./etl/transform/migrations/weather_conditions.py
    name: create_weather_conditions
    product:
      data: '{{transform_path}}/migrations/weather_conditions.csv'
      nb: ./etl/transform/migrations/output/weather_conditions.ipynb
    params:
      extract_path: '{{extract_path}}'
      transform_path: '{{transform_path}}'
  - source: ./etl/transform/migrations/wind_directions.py
    name: create_wind_directions
    product:
      data: '{{transform_path}}/migrations/wind_directions.csv'
      nb: ./etl/transform/migrations/output/wind_directions.ipynb
    params:
      extract_path: '{{extract_path}}'
      transform_path: '{{transform_path}}'
  - source: ./etl/transform/migrations/moon_phases.py
    name: create_moon_phases
    product:
      data: '{{transform_path}}/migrations/moon_phases.csv'
      nb: ./etl/transform/migrations/output/moon_phases.ipynb
    params:
      extract_path: '{{extract_path}}'
      transform_path: '{{transform_path}}'